Repository rotorgames/Rg.Plugins.Popup, pull requests merged in 2021-03, with the labels that each got.

#659 Setting UIWindowLevel.Normal during removal
  Rg.Plugins.Popup/Platforms/Ios/Impl/PopupPlatformIos.cs
  Samples/Demo/Demo.csproj
  Samples/Demo/Pages/MainPage.xaml
  Samples/Demo/Pages/MainPage.xaml.cs
  Samples/Demo/Pages/TestCurrentViewController.xaml
  Samples/Demo/Pages/TestCurrentViewController.xaml.cs
Labels: bug, need-review

#660 Fix: Fix the popup windows issues for iOS 13+ when the multi scene is enabled
  Rg.Plugins.Popup/Platforms/Ios/Impl/PopupPlatformIos.cs
  Rg.Plugins.Popup/Platforms/Ios/Platform/PopupWindow.cs
Labels: bug, fixed, need-review

#657 Accessibility upgrade
  Rg.Plugins.Popup/Pages/PopupPage.cs
  Rg.Plugins.Popup/Platforms/Android/Impl/PopupPlatformDroid.cs
  Rg.Plugins.Popup/Platforms/Mac/Extensions/PlatformExtension.cs
  Samples/Demo.Droid/MainActivity.cs
  Samples/Demo/Pages/FirstPopupPage.xaml
  Samples/Demo/Pages/ListViewPage.xaml
  Samples/Demo/Pages/LoginPopupPage.xaml
Labels: enhancement, fixed, need-review
